# Generated by Django 3.2 on 2021-11-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('basal_inf', models.FloatField()),
                ('basal_sup', models.FloatField()),
                ('thermal_constant', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCultures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acummulated_degrees', models.FloatField(blank=True, default=0.0)),
                ('culture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='culture', to='cultures.culture')),
            ],
        ),
    ]
