# Generated by Django 3.2 on 2021-11-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0002_usercultures_farmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercultures',
            old_name='acummulated_degrees',
            new_name='accumulated_degrees',
        ),
    ]
